language: node_js
node_js:
- '8'
branches:
  only:
  - v2
script:
- yarn test
- yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: v2
